# This will run on Travis' 'new' container-based infrastructure
sudo: false

branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-latex
      - graphviz

# Create temporary folder in the cloned repo
before_script: 
  - mkdir tmp_docs

# Build your code e.g. by calling make
script:
  - doxygen tools/doxygen_config

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: tmp_docs
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
