name: Build tester

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: [ linux, macOS ]

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./tests/automatic_tester/
      run: make -f automatic_tester.mak
